### ISSUE TITLE
Add continuous integration (Travis CI)

### ISSUE THREAD

**Issue by sdhutchins** [datasnakes/renv#41]
Check out https://github.com/sdispater/poetry/issues/366

**Comment by sdhutchins** [comment]
```yaml
language: python
python:
  - 3.6

install:
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - export PATH=$PATH:~/.poetry/bin
  - poetry install
```

**Comment by sdhutchins** [comment]
A fully fleshed example ():
```yaml
language: python
python:
- '2.7'
- '3.5'
- '3.6'
matrix:
  include:
  - python: 3.7
    dist: xenial
before_install:
- pip install poetry
install:
- poetry install -v
- pip install tox-travis
script:
- tox
before_deploy:
- poetry config http-basic.pypi $PYPI_USER $PYPI_PASSWORD
- poetry build
deploy:
  provider: script
  script: poetry publish
  on:
    tags: true
    condition: "$TRAVIS_PYTHON_VERSION == 3.7"
env:
  global:
  - secure: [REDACTED]
  - secure: [REDACTED]
```
